apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: read-logs
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          securityContext:
            privileged: true
          command: ["tail"]
          args: ["-f", "/var/log/syslog"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
