apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pv-pod
  labels:
    app: data-pv-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pv-pod
  template:
    metadata:
      labels:
        app: data-pv-pod
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: busybox
          image: busybox
          command: [ "/bin/sh", "-c", "while true; do date >> /shared-busybox/data.txt; sleep 5; done" ]
          volumeMounts:
            - name: shared-data
              mountPath: /shared-busybox
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: shared-data
              mountPath: /shared-multitool
