apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-app
  labels:
    app: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - mountPath: /shared-data
              name: volume-01
      volumes:
        - name: volume-01
          persistentVolumeClaim:
            claimName: pvc-01